# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='data_locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('appartament', models.CharField(max_length=200)),
                ('floor', models.CharField(max_length=200)),
                ('house', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=120)),
                ('Country', models.CharField(max_length=120)),
                ('callnames', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=120)),
                ('secret_call', models.CharField(max_length=120)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='event_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('contact_date', models.DateField(auto_now_add=True, verbose_name='Conversation Date')),
                ('contact_time', models.TimeField(auto_now_add=True, verbose_name='Conversation Time')),
            ],
        ),
    ]
