# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nutrition_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='event_food',
        ),
        migrations.AddField(
            model_name='data_locality',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/beerthumbs/'),
        ),
    ]
